SELECT pid                          , application_name                           , to_char((clock_timestamp() - query_start), 'HH24 hrs MI "minutes" SS "seconds"     '),                           usename , query FROM pg_stat_activity                             where application_name like 'IO.%'                           order by application_name asc  , age(clock_timestamp(), query_start) desc;
SELECT pid                          , application_name                           , to_char((clock_timestamp() - query_start), 'HH24 hrs MI "minutes" SS "seconds"     '),                           usename , query FROM pg_stat_activity                             where application_name like 'IO.%'                           order by application_name asc  , age(clock_timestamp(), query_start) desc;
select max(fr.age), max(fr.weight), max(fr.submit_date),min(fr.age), min(fr.weight), min(fr.submit_date)                                   from tb_ctfaers_report fr                                   where fr.umls @> ARRAY[text(?)];
select count(1) from (select distinct on ("report_id") "report_id" from "tb_ctfaers_report") x2;
select x2.x3, count(1) from (select distinct on ("year", "report_id") "year" as x3, "report_id" as x4 from "tb_ctfaers_report" where "umls" @> '{C0015672}') x2 group by x2.x3 order by x2.x3;
select count(1) from (select distinct on ("report_id") "report_id" from "tb_ctfaers_report") x2;
select distinct "report_id", "case_id", "age", "outcome", "weight", "sex", "reporter", "submit_date", "umls", "case_id", "inchikeys", "drugnames", "duplicated" from "tb_ctfaers_report" where "umls" @> '{C0015672}' order by "submit_date" desc limit 50000;
select x2.x3, x2.x4, x5."name", x5."spaces_visible", x6."label", x6."color" from (select unnest(x7.x8) as x3, count(1) as x4 from (select distinct on ("inchikeys", "report_id") "inchikeys" as x8, "report_id" as x9 from "tb_ctfaers_report" where "umls" @> '{C0015672}') x7 group by unnest(x7.x8)) x2, "tb_classification_tree" x6, "tb_molecule_classification" x10, "tb_chemical_space" x5 where (((x10."tree_id" = 'ATC') and (x5."inchikey" = x10."inchikey")) and (((x6."tree_id" = 'ATC') and (nlevel(x6."path") = 1)) and (x10."path" <@ x6."path"))) and (x10."inchikey" = x2.x3);
select "report_id", "druginchi", "route", "indication" from "tb_ctfaers_report_drug" where "report_id" in (select distinct on ("report_id", "case_id", "age", "outcome", "weight", "sex", "reporter", "submit_date", "umls", "case_id", "inchikeys", "drugnames", "duplicated") "report_id" from "tb_ctfaers_report" where "umls" @> '{C0015672}' order by "submit_date" desc limit 50000);
select count(1) from (select distinct on ("report_id") "report_id" from "tb_ctfaers_report" where "umls" @> '{C0015672}') x2
